package com.nammamedmate.pos.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.nammamedmate.kernel.error.AppException;
import com.nammamedmate.kernel.ratelimit.InMemoryRateLimiter;
import com.nammamedmate.pos.application.port.out.OfferStore;
import com.nammamedmate.pos.application.port.out.PosPlanPort;
import com.nammamedmate.pos.domain.DiscountType;
import com.nammamedmate.pos.domain.OfferAppliesTo;
import com.nammamedmate.pos.domain.PharmacyOffer;
import com.nammamedmate.pos.domain.PosCartItem;
import com.nammamedmate.security.AuthRole;
import com.nammamedmate.security.MedmatePrincipal;
import com.nammamedmate.security.TokenScope;
import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class OfferServiceAcTest {

  static final Instant NOW = Instant.parse("2026-07-24T12:00:00Z");

  @Mock OfferStore store;
  @Mock PosPlanPort plan;

  OfferService service;
  UUID pharmacy = UUID.randomUUID();
  UUID staff = UUID.randomUUID();
  MedmatePrincipal owner =
      new MedmatePrincipal(staff, AuthRole.PHARMACY_OWNER, pharmacy, TokenScope.FULL, "j");
  MedmatePrincipal freeOwner =
      new MedmatePrincipal(staff, AuthRole.PHARMACY_OWNER, pharmacy, TokenScope.FULL, "j");

  @BeforeEach
  void setUp() {
    Clock clock = Clock.fixed(NOW, ZoneOffset.UTC);
    when(plan.growthFeaturesEnabled()).thenReturn(true);
    when(store.insert(any())).thenAnswer(inv -> inv.getArgument(0));
    when(store.update(any())).thenAnswer(inv -> inv.getArgument(0));
    service = new OfferService(store, plan, new InMemoryRateLimiter(clock), clock);
  }

  @Test
  void ac_planFeatureLockedOnCreate() {
    when(plan.growthFeaturesEnabled()).thenReturn(false);
    assertThatThrownBy(
            () ->
                service.create(
                    freeOwner,
                    Map.of(
                        "title",
                        "Offer",
                        "discount_type",
                        "PERCENTAGE",
                        "discount_value",
                        10,
                        "applies_to",
                        "ALL",
                        "valid_from",
                        "2026-07-01",
                        "valid_until",
                        "2026-07-31")))
        .extracting(e -> ((AppException) e).code())
        .isEqualTo("PLAN_FEATURE_LOCKED");
  }

  @Test
  void ac_discountExceedsPlatformLimit() {
    assertThatThrownBy(
            () ->
                service.create(
                    owner,
                    Map.of(
                        "title",
                        "Too big",
                        "discount_type",
                        "PERCENTAGE",
                        "discount_value",
                        60,
                        "applies_to",
                        "ALL",
                        "valid_from",
                        "2026-07-01",
                        "valid_until",
                        "2026-07-31")))
        .extracting(e -> ((AppException) e).code())
        .isEqualTo("DISCOUNT_EXCEEDS_PLATFORM_LIMIT");
  }

  @Test
  void ac_autoGeneratedCouponCode() {
    when(store.couponExists(eq(pharmacy), any(), isNull())).thenReturn(false);
    Map<String, Object> data =
        service.create(
            owner,
            Map.of(
                "title",
                "Auto code",
                "discount_type",
                "PERCENTAGE",
                "discount_value",
                10,
                "applies_to",
                "ALL",
                "valid_from",
                "2026-07-01",
                "valid_until",
                "2026-07-31"));
    String code = data.get("coupon_code").toString();
    assertThat(code).hasSize(6).matches("[A-Z0-9]{6}");
  }

  @Test
  void ac_validateValidCoupon() {
    UUID offerId = UUID.randomUUID();
    UUID productId = UUID.randomUUID();
    PharmacyOffer offer =
        offer(
            offerId,
            "SAVE10",
            DiscountType.PERCENTAGE,
            10,
            OfferAppliesTo.ALL,
            List.of(),
            true,
            LocalDate.of(2026, 7, 1),
            LocalDate.of(2026, 7, 31),
            0,
            0);
    when(store.findByCoupon(pharmacy, "SAVE10")).thenReturn(Optional.of(offer));
    Map<String, Object> data =
        service.validate(
            owner,
            Map.of(
                "coupon_code",
                "SAVE10",
                "cart_total",
                420.00,
                "product_ids",
                List.of(productId.toString())));
    assertThat(data.get("is_valid")).isEqualTo(true);
    assertThat((BigDecimal) data.get("discount_amount")).isEqualByComparingTo("42.00");
  }

  @Test
  void ac_validateCategoryNotApplicable() {
    UUID offerId = UUID.randomUUID();
    UUID antibiotics = UUID.randomUUID();
    UUID productId = UUID.randomUUID();
    UUID otherCat = UUID.randomUUID();
    PharmacyOffer offer =
        offer(
            offerId,
            "ANTIBI10",
            DiscountType.PERCENTAGE,
            10,
            OfferAppliesTo.CATEGORY,
            List.of(antibiotics),
            true,
            LocalDate.of(2026, 7, 1),
            LocalDate.of(2026, 7, 31),
            0,
            0);
    when(store.findByCoupon(pharmacy, "ANTIBI10")).thenReturn(Optional.of(offer));
    when(store.productCategoryIds(pharmacy, List.of(productId)))
        .thenReturn(Map.of(productId, otherCat));
    when(store.categoryNames(List.of(antibiotics))).thenReturn(Map.of(antibiotics, "Antibiotics"));
    Map<String, Object> data =
        service.validate(
            owner,
            Map.of(
                "coupon_code",
                "ANTIBI10",
                "cart_total",
                100.00,
                "product_ids",
                List.of(productId.toString())));
    assertThat(data.get("is_valid")).isEqualTo(false);
    assertThat(data.get("error_code")).isEqualTo("COUPON_NOT_APPLICABLE");
  }

  @Test
  void ac_deleteWithRedemptionsSetsExpired() {
    UUID offerId = UUID.randomUUID();
    PharmacyOffer cur =
        offer(
            offerId,
            "KEEP",
            DiscountType.PERCENTAGE,
            10,
            OfferAppliesTo.ALL,
            List.of(),
            true,
            LocalDate.of(2026, 7, 1),
            LocalDate.of(2026, 12, 31),
            0,
            50);
    when(store.findById(pharmacy, offerId)).thenReturn(Optional.of(cur));
    Map<String, Object> data = service.delete(owner, offerId);
    assertThat(data.get("action")).isEqualTo("SET_EXPIRED");
    assertThat(data.get("valid_until")).isEqualTo("2026-07-24");
    ArgumentCaptor<PharmacyOffer> cap = ArgumentCaptor.forClass(PharmacyOffer.class);
    verify(store).update(cap.capture());
    assertThat(cap.getValue().validUntil()).isEqualTo(LocalDate.of(2026, 7, 24));
    assertThat(cap.getValue().active()).isFalse();
  }

  @Test
  void ac_highestCounterOfferWins() {
    UUID productId = UUID.randomUUID();
    UUID lowId = UUID.randomUUID();
    UUID highId = UUID.randomUUID();
    PharmacyOffer low =
        offer(
            lowId,
            "LOW",
            DiscountType.PERCENTAGE,
            5,
            OfferAppliesTo.PRODUCT,
            List.of(productId),
            true,
            LocalDate.of(2026, 7, 1),
            LocalDate.of(2026, 7, 31),
            0,
            0);
    PharmacyOffer high =
        offer(
            highId,
            "HIGH",
            DiscountType.PERCENTAGE,
            15,
            OfferAppliesTo.PRODUCT,
            List.of(productId),
            true,
            LocalDate.of(2026, 7, 1),
            LocalDate.of(2026, 7, 31),
            0,
            0);
    when(store.listActiveCounterOffers(eq(pharmacy), any())).thenReturn(List.of(low, high));
    when(store.productCategoryIds(eq(pharmacy), any())).thenReturn(Map.of());
    PosCartItem item =
        PosCartItem.compute(
            UUID.randomUUID(),
            UUID.randomUUID(),
            productId,
            "P",
            UUID.randomUUID(),
            "BN",
            LocalDate.of(2027, 1, 1),
            1,
            false,
            10_000L,
            12,
            false,
            1,
            "H",
            NOW);
    Optional<OfferService.AppliedOffer> best =
        service.bestCounterOffer(pharmacy, List.of(item), true);
    assertThat(best).isPresent();
    assertThat(best.get().offer().id()).isEqualTo(highId);
    assertThat(best.get().discountAmountPaise()).isEqualTo(1_500L);
  }

  @Test
  void ac_toggleFlipsActive() {
    UUID offerId = UUID.randomUUID();
    AtomicReference<PharmacyOffer> ref =
        new AtomicReference<>(
            offer(
                offerId,
                "T",
                DiscountType.PERCENTAGE,
                10,
                OfferAppliesTo.ALL,
                List.of(),
                true,
                LocalDate.of(2026, 7, 1),
                LocalDate.of(2026, 7, 31),
                0,
                0));
    when(store.findById(pharmacy, offerId)).thenAnswer(inv -> Optional.of(ref.get()));
    when(store.update(any()))
        .thenAnswer(
            inv -> {
              PharmacyOffer o = inv.getArgument(0);
              ref.set(o);
              return o;
            });
    Map<String, Object> first = service.toggle(owner, offerId);
    assertThat(first.get("is_active")).isEqualTo(false);
    Map<String, Object> second = service.toggle(owner, offerId);
    assertThat(second.get("is_active")).isEqualTo(true);
  }

  private PharmacyOffer offer(
      UUID id,
      String code,
      DiscountType type,
      long value,
      OfferAppliesTo appliesTo,
      List<UUID> scope,
      boolean active,
      LocalDate from,
      LocalDate until,
      int max,
      int total) {
    return new PharmacyOffer(
        id, pharmacy, "Title", code, type, value, appliesTo, scope, false, true, active, from,
        until, max, total, NOW, NOW);
  }
}
